(** Adapted from "Elements of Set Theory" Chapter 8 **)
(** Coq coding by choukh, Aug 2021 **)

Require Export ZFC.Elements.EST8_7.
Import OrdinalClass 𝐎𝐍Operation.

Local Hint Resolve
  add_ran mul_ran exp_ran
  ordAdd_ran ordMul_ran preOrdExp_ran ordExp_ran : core.

(*** EST第八章8：迭代幂次，ε数 ***)

(** ε数 **)
(* please see LargeOrdinal/EpsilonNumbers.v *)

(** 迭代幂次 **)
(* see also LargeOrdinals/NormalTetration.v *)
Definition OrdTetL := λ α, Operation α (OrdExp α).
Notation "α ^^ᴸ β" := (OrdTetL α β) (at level 25) : OrdArith_scope.

Theorem ordTetL_0 : ∀α ⋵ 𝐎𝐍, α ^^ᴸ 0 = α.
Proof. intros α H. apply operation_0; auto. Qed.

Theorem ordTetL_suc : ∀ α β ⋵ 𝐎𝐍, α ^^ᴸ β⁺ = α ^ (α ^^ᴸ β).
Proof. intros α Hα β Hβ. apply operation_suc; auto. Qed.

Theorem ordTetL_limit : ∀α ⋵ 𝐎𝐍, continuous (OrdTetL α).
Proof. intros α Hα. apply operation_limit; auto. Qed.

Theorem ordTetL_ran : ∀ α β ⋵ 𝐎𝐍, α ^^ᴸ β ⋵ 𝐎𝐍.
Proof. intros α Hα β Hβ. apply operation_operative; auto. Qed.
Local Hint Resolve ordTetL_ran : core.

Theorem ordTetL_1_r : ∀α ⋵ 𝐎𝐍, α ^^ᴸ 1 = α ^ α.
Proof.
  intros α H. rewrite pred, ordTetL_suc, ordTetL_0; auto.
Qed.

Theorem ordTetL_1_l : ∀α ⋵ 𝐎𝐍, 1 ^^ᴸ α = 1.
Proof with neauto.
  ord_induction. intros α Hα IH.
  ord_destruct α.
  - subst. rewrite ordTetL_0...
  - destruct Hsuc as [β [Hβ Heq]]. subst.
    rewrite ordTetL_suc, ordExp_1_l...
  - rewrite ordTetL_limit... ext.
    + apply FUnionE in H as [β [Hβ H]]. rewrite IH in H...
    + rewrite one in H. apply SingE in H. subst.
      eapply FUnionI. apply ord_neq_0_gt_0...
      rewrite ordTetL_0, pred...
Qed.

Lemma ordTetL_eq_0 : ∀ α β ⋵ 𝐎𝐍, α ^^ᴸ β = 0 → α = 0.
Proof with eauto.
  intros α Hα β Hβ. generalize dependent β.
  ord_induction. intros β Hβ IH H.
  ord_destruct β.
  - subst. rewrite ordTetL_0 in H...
  - destruct Hsuc as [γ [Hγ Heq]]. subst.
    rewrite ordTetL_suc in H...
    apply ordExp_eq_0 in H...
  - rewrite ordTetL_limit in H...
    apply union_eq_empty in H as [].
    + apply repl_eq_empty in H. exfalso...
    + apply EmptyNE in H0 as [γ Hγ].
      assert (Hoγ: γ ⋵ 𝐎𝐍). eapply ord_is_ords...
      apply sucord_in_limord in Hγ...
      eapply repl_eq_1 in Hγ as H0...
Qed.

Lemma ordAdd_eq_1 : ∀ α β ⋵ 𝐎𝐍, α + β = 1 →
  α = 0 ∧ β = 1 ∨ α = 1 ∧ β = 0.
Proof with neauto.
  intros α Hα β Hβ H.
  ord_destruct α; subst.
  - rewrite ordAdd_0_l in H...
  - destruct Hsuc as [γ [Hγ Heq]]. subst.
    ord_destruct β.
    + subst. rewrite ordAdd_0_r in H...
    + exfalso. destruct Hsuc as [δ [Hδ Heq]]. subst.
      rewrite <- (ordAdd_1_r δ), <- ordAdd_assoc in H...
      rewrite (ordAdd_1_r), pred in H...
      apply ord_suc_injective in H...
      apply ordAdd_eq_0 in H as []... eapply suc_neq_0...
    + exfalso. apply limord_ge_ω in Hlim...
      apply (ord_irrefl 1)... rewrite <- H at 2.
      eapply ord_trans_lt_le. auto. apply embed_ran.
      eapply ord_trans_le... apply ordAdd_enlarge_l...
  - exfalso.
    destruct (classic (β = 0)). {
      subst. rewrite ordAdd_0_r in H...
      apply (limord_iff_not_sucord α)... exists 0...
    }
    apply limord_ge_ω in Hlim...
    apply (ord_irrefl 1)... rewrite <- H at 2.
    eapply ord_trans. auto. apply embed_ran.
    eapply ord_trans_le_lt... apply ordAdd_enlarge_r...
Qed.

Lemma ordMul_eq_1 : ∀ α β ⋵ 𝐎𝐍, α ⋅ β = 1 → α = 1 ∧ β = 1.
Proof with neauto.
  intros α Hα β Hβ H. ord_destruct β.
  - subst. rewrite ordMul_0_r in H... exfalso...
  - destruct Hsuc as [γ [Hγ Heq]]. subst.
    rewrite ordMul_suc in H...
    apply ordAdd_eq_1 in H as [[H0 H1]|[H1 H0]]...
    + apply ordMul_eq_0 in H0 as []...
      * exfalso. subst...
      * split... subst...
    + rewrite H0 in H1. rewrite ordMul_0_l in H1... exfalso...
  - exfalso.
    destruct (classic (α = 0)). subst. rewrite ordMul_0_l in H...
    destruct (classic (α = 1)). {
      subst. rewrite ordMul_1_l in H...
      apply (limord_iff_not_sucord β)... exists 0...
    }
    apply limord_ge_ω in Hlim...
    apply (ord_irrefl 1)... rewrite <- H at 2.
    eapply ord_trans_lt_le. auto. apply embed_ran.
    eapply ord_trans_le... apply ordMul_enlarge_l...
Qed.

Lemma preOrdExp_eq_1 : ∀ α β ⋵ 𝐎𝐍, α ^ᵖ β = 1 →
  α = 1 ∨ β = 0 ∨ β ≠ 0 ∧ β ⋵ 𝐎𝐍ˡⁱᵐ ∧ α = 0.
Proof with neauto.
  intros α Hα β Hβ H. ord_destruct β...
  - destruct Hsuc as [γ [Hγ Heq]]. subst.
    rewrite preOrdExp_suc in H...
    apply ordMul_eq_1 in H as []...
  - destruct (classic (α = 0))...
    destruct (classic (α = 1))...
    exfalso. apply limord_ge_ω in Hlim...
    apply (ord_irrefl 1)... rewrite <- H at 2.
    eapply ord_trans_lt_le. auto. apply embed_ran.
    eapply ord_trans_le... apply preOrdExp_enlarge_l...
Qed.

Lemma ordExp_eq_1 : ∀ α β ⋵ 𝐎𝐍, α ^ β = 1 → α = 1 ∨ β = 0.
Proof with neauto.
  intros α Hα β Hβ H. ord_destruct β.
  - subst. rewrite ordExp_0_r in H...
  - destruct Hsuc as [γ [Hγ Heq]]. subst.
    rewrite ordExp_suc in H...
    apply ordMul_eq_1 in H as []...
  - destruct (classic (α = 1))...
    exfalso. unfold OrdExp in H.
    destruct (ixm (α = 0)); destruct (ixm (β = 0))...
    apply limord_ge_ω in Hlim...
    apply (ord_irrefl 1)... rewrite <- H at 2.
    eapply ord_trans_lt_le. auto.
    apply embed_ran. eapply ord_trans_le...
    apply preOrdExp_enlarge_l...
Qed.

Lemma ordTetL_gt_1 : ∀ α β ⋵ 𝐎𝐍, 1 ∈ α → 1 ∈ α ^^ᴸ β.
Proof with neauto.
  intros α Hα. ord_induction. intros β Hβ IH H.
  ord_destruct β.
  - subst. rewrite ordTetL_0...
  - destruct Hsuc as [γ [Hγ Heq]]. subst.
    rewrite ordTetL_suc... eapply ord_trans...
    apply ordExp_enlarge_r...
  - rewrite ordTetL_limit...
    apply EmptyNE in H0 as [γ Hγ].
    assert (Hoγ: γ ⋵ 𝐎𝐍). eapply ord_is_ords...
    eapply FUnionI. apply sucord_in_limord...
    eapply ord_trans_lt_le. auto. apply IH...
    rewrite ordTetL_suc... apply ordExp_enlarge_l...
Qed.

Theorem ordTetL_eq_1 : ∀ α β ⋵ 𝐎𝐍, α ^^ᴸ β = 1 → α = 0 ∨ α = 1.
Proof with neauto.
  intros α Hα. ord_induction. intros β Hβ IH H.
  ord_destruct β.
  - subst. rewrite ordTetL_0 in H...
  - destruct Hsuc as [γ [Hγ Heq]]. subst.
    rewrite ordTetL_suc in H...
    apply ordExp_eq_1 in H as []...
    apply ordTetL_eq_0 in H...
  - destruct (classic (α = 0))...
    destruct (classic (α = 1))... exfalso.
    apply (ord_irrefl 1)... rewrite <- H at 2.
    apply ordTetL_gt_1...
Qed.

Fact ordTetL_is_limord_l : ∀α ⋵ 𝐎𝐍, ∀𝜆 ⋵ 𝐎𝐍ˡⁱᵐ, 𝜆 ≠ 0 → 𝜆 ^^ᴸ α ⋵ 𝐎𝐍ˡⁱᵐ.
Proof with nauto.
  ord_induction. intros α Hα IH 𝜆 H𝜆 H0.
  ord_destruct α.
  - subst. rewrite ordTetL_0...
  - destruct Hsuc as [β [Hβ Heq]]. subst.
    rewrite ordTetL_suc... apply ordExp_is_limord_l...
    apply ordTetL_gt_1... eapply ord_trans_lt_le. auto.
    apply embed_ran. apply limord_ge_ω...
  - rewrite ordTetL_limit...
    apply union_of_limords_is_limord. intros x Hx.
    apply ReplAx in Hx as [β [Hβ Hx]]. subst x. apply IH...
Qed.

Lemma tetL_ran : ∀ m n ∈ ω, m ^^ᴸ n ∈ ω.
Proof with auto.
  intros k Hk n Hn. ω_induction n.
  - rewrite ordTetL_0...
  - rewrite ordTetL_suc, fin_ordExp_eq_exp...
Qed.
Local Hint Resolve tetL_ran : core.

Lemma tetL_preserve_base_lt : ∀ m n p ∈ ω, m ≠ 0 → n ≠ 0 →
  m ∈ n ↔ m ^^ᴸ p ∈ n ^^ᴸ p.
Proof with eauto.
  assert (Hright: ∀ m n p ∈ ω, m ≠ 0 → n ≠ 0 → m ∈ n → m ^^ᴸ p ∈ n ^^ᴸ p). {
    intros m Hm n Hn p Hp Hm0 Hn0 H.
    generalize dependent n. generalize dependent m.
    ω_induction p; intros k Hk Hk0 n Hn Hn0 H.
    - rewrite ordTetL_0, ordTetL_0...
    - assert (Hmp: m⁺ ∈ ω). apply ω_inductive...
      assert (H0: k ^^ᴸ m ≠ 0). intros H0. apply ordTetL_eq_0 in H0...
      rewrite ordTetL_suc, ordTetL_suc...
      repeat rewrite fin_ordExp_eq_exp...
      eapply lt_le_trans. auto.
      apply exp_preserve_base_lt; revgoals...
      apply exp_preserve_exponent_le...
  }
  intros m Hm n Hn p Hp Hm0 Hn0. split. apply Hright...
  intros H. destruct (classic (m = n)).
  - subst. exfalso. eapply nat_irrefl; revgoals...
  - apply nat_connected in H0 as []...
    pose proof (Hright n Hn m Hm p Hp Hn0 Hm0 H0).
    exfalso. eapply nat_not_lt_gt; revgoals...
Qed.

Lemma tetL_enlarge_l : ∀ m n ∈ ω, 1 ∈ n → m ∈ n ^^ᴸ m.
Proof with neauto.
  intros k Hk. ω_induction k; intros n Hn Hn0.
  - rewrite ordTetL_0... apply ord_neq_0_gt_0...
    apply ord_gt_1_neq_0_1...
  - rewrite ordTetL_suc... pose proof (IH n Hn Hn0).
    apply lt_iff_suc_le in H...
    eapply ord_trans_le_lt. auto. apply H.
    rewrite fin_ordExp_eq_exp... apply exp_enlarge_l...
Qed.

Lemma ordTetL_2_ω : 2 ^^ᴸ ω = ω.
Proof with neauto.
  ext.
  - rewrite ordTetL_limit in H...
    apply FUnionE in H as [k [Hk Hx]]. eapply ω_trans...
  - rewrite ordTetL_limit... eapply FUnionI...
    apply tetL_enlarge_l... rewrite (pred 2)...
Qed.

(** 无限结合律，左侧严格放大 **)

Lemma ordAdd_arbitrary_assoc : ∀α ⋵ 𝐎𝐍, ∀n ∈ ω, α + α ⋅ n = α ⋅ n + α.
Proof with auto.
  intros α Hα n Hn. ω_induction n.
  - rewrite ordMul_0_r, ordAdd_0_r, ordAdd_0_l...
  - rewrite ordMul_suc... rewrite <- IH at 2... rewrite ordAdd_assoc...
Qed.

Lemma ordAdd_enlarge_l_strictly : ∀α ⋵ 𝐎𝐍, ∀n ∈ ω, ∀β ∈ α ⋅ n, β ∈ α + β.
Proof with neauto; try congruence.
  intros α Hα n Hn. ω_induction n; intros β Hβ.
  - rewrite <- zero, ordMul_0_r in Hβ... exfalso0.
  - destruct (classic (β ∈ α ⋅ m)). apply IH...
    assert (Hoβ: β ⋵ 𝐎𝐍). apply (ord_is_ords (α ⋅ m⁺))...
    rewrite ordMul_suc, <- ordAdd_arbitrary_assoc in Hβ...
    apply ord_le_iff_not_gt in H as []...
    apply (ordAdd_preserve_lt α) in H... eapply ord_trans...
Qed.

Lemma ordMul_arbitrary_assoc : ∀α ⋵ 𝐎𝐍, ∀n ∈ ω, α ⋅ α ^ n = α ^ n ⋅ α.
Proof with auto.
  intros α Hα n Hn. ω_induction n.
  - rewrite ordExp_0_r, ordMul_1_r, ordMul_1_l...
  - rewrite ordExp_suc... rewrite <- IH at 2... rewrite ordMul_assoc...
Qed.

Lemma ordMul_enlarge_l_strictly : ∀α ⋵ 𝐎𝐍, ∀n ∈ ω, ∀β ∈ α ^ n, β ≠ 0 → β ∈ α ⋅ β.
Proof with neauto; try congruence.
  intros α Hα n Hn β Hβ Hβ0.
  destruct (classic (α = 0)) as [|Hα0]. {
    subst. destruct (classic (n = 0)). {
      subst. rewrite ordExp_0_r in Hβ...
      rewrite one in Hβ. apply SingE in Hβ. exfalso...
    }
    rewrite ordExp_0_l in Hβ... exfalso0.
  }
  generalize dependent β.
  ω_induction n; intros β Hβ Hβ0.
  - rewrite <- zero, ordExp_0_r in Hβ...
    rewrite one in Hβ. apply SingE in Hβ. exfalso...
  - destruct (classic (β ∈ α ^ m)). apply IH...
    assert (Hoβ: β ⋵ 𝐎𝐍). apply (ord_is_ords (α ^ m⁺))...
    rewrite ordExp_suc, <- ordMul_arbitrary_assoc in Hβ...
    apply ord_le_iff_not_gt in H as []...
    apply (ordMul_preserve_lt α) in H... eapply ord_trans...
Qed.

Lemma ordExp_enlarge_l_strictly : ∀α ⋵ 𝐎𝐍, 1 ∈ α → ∀n ∈ ω, ∀β ∈ α ^^ᴸ n, β ∈ α ^ β.
Proof with neauto; try congruence.
  intros α Hα Hα1 n Hn. ω_induction n; intros x Hx.
  - destruct (classic (x = 0)). {
      subst. rewrite ordExp_0_r, pred, pred...
    }
    rewrite <- zero, ordTetL_0 in Hx...
    apply ordExp_enlarge_lt... 1-2: eapply ord_is_ords...
  - destruct (classic (x ∈ α ^^ᴸ m)). apply IH...
    assert (Hox: x ⋵ 𝐎𝐍). apply (ord_is_ords (α ^^ᴸ m⁺))...
    rewrite ordTetL_suc in Hx...
    apply ord_le_iff_not_gt in H as []...
    apply (ordExp_preserve_lt α) in H... eapply ord_trans...
Qed.

(** 吸收律 **)

(* Those α that ω ⋸ α are all fixed points for n_addition.
  Please see also LargeOrdinal/LowerFixedPoint.v *)
Theorem ordAdd_1_absorption : ∀α ⋵ 𝐎𝐍, ω ⋸ α → 1 + α = α.
Proof with neauto.
  ord_induction. intros α Hα IH Hle.
  destruct Hle; revgoals. {
    subst. apply ordAdd_1_ω.
  }
  ord_destruct α.
  - subst. exfalso0.
  - destruct Hsuc as [β [Hβ Heq]]. subst.
    rewrite ordAdd_suc, IH... apply ord_le_iff_lt_suc...
  - rewrite ordAdd_limit... ext ξ Hξ.
    + apply FUnionE in Hξ as [β [Hβ Hξ]].
      destruct (classic (β ∈ ω)).
      * eapply ord_trans... rewrite ordAdd_1_l...
        apply sucord_in_limord...
      * rewrite IH in Hξ... eapply ord_trans...
        apply ord_le_iff_not_gt... eapply ord_is_ords...
    + assert (Hξo: ξ ⋵ 𝐎𝐍). eapply ord_is_ords...
      destruct (classic (ξ ∈ ω)) as [|Hle].
      * eapply FUnionI... rewrite ordAdd_1_l...
      * apply ord_le_iff_not_gt in Hle...
        eapply FUnionI. apply sucord_in_limord...
        rewrite ordAdd_suc, IH...
Qed.

Corollary ordAdd_n_absorption : ∀α ⋵ 𝐎𝐍, ∀n ∈ ω, ω ⋸ α → n + α = α.
Proof with neauto.
  intros α Hα n Hn Hle.
  ω_induction n. rewrite ordAdd_0_l...
  rewrite <- ordAdd_1_r, ordAdd_assoc, ordAdd_1_absorption...
Qed.

(* ω幂对加法的吸收律 *)
Corollary ordAdd_ω_pow_absorption : ∀β ⋵ 𝐎𝐍, ∀α ∈ β, ω ^ α + ω ^ β = ω ^ β.
Proof with neauto.
  intros β Hβ α Hlt. assert (α ⋸ β)...
  assert (Hα: α ⋵ 𝐎𝐍). eapply ord_is_ords...
  apply ord_subtraction in H as [δ [[Hδ Hsum] _]]... subst.
  rewrite <- ordExp_add... rewrite <- (ordMul_1_r (ω ^ α)) at 1...
  rewrite <- ordMul_distr... f_equal. apply ordAdd_1_absorption...
  rewrite <- ordExp_1_r at 1 3... apply ordExp_preserve_le_r...
  apply ord_le_iff_not_gt... intros H.
  rewrite one in H. apply SingE in H. subst.
  rewrite ordAdd_0_r in Hlt... eapply ord_irrefl...
Qed.

Theorem ordMul_n_ω : ∀n ∈ ω, n ≠ 0 → n ⋅ ω = ω.
Proof with neauto.
  intros n Hn. ω_induction n; intros H0. exfalso...
  assert (Hmp: m⁺ ∈ ω). apply ω_inductive...
  ext.
  - rewrite ordMul_limit in H...
    apply FUnionE in H as [k [Hk Hx]].
    eapply ω_trans... rewrite fin_ordMul_eq_mul...
  - destruct (classic (m = 0)).
    + subst. rewrite ordMul_1_l...
    + rewrite <- IH, ordMul_limit in H... rewrite ordMul_limit...
      apply FUnionE in H as [k [Hk Hx]].
      eapply FUnionI... eapply ord_trans...
      rewrite fin_ordMul_eq_mul, fin_ordMul_eq_mul...
      apply mul_preserve_lt... intros H. subst.
      rewrite ordMul_0_r in Hx... exfalso0.
Qed.

Theorem ordExp_n_ω : ∀n ∈ ω, 1 ∈ n → n ^ ω = ω.
Proof with neauto.
  intros n Hn. ω_induction n; intros H1. exfalso0.
  assert (Hmp: m⁺ ∈ ω). apply ω_inductive...
  ext.
  - rewrite ordExp_limit in H...
    apply FUnionE in H as [k [Hk Hx]].
    eapply ω_trans... rewrite fin_ordExp_eq_exp...
  - destruct (classic (x = 0)) as [|Hx0]. {
      subst. apply ord_neq_0_gt_0... intros H0.
      apply ordExp_eq_0 in H0... eapply suc_neq_0...
    }
    destruct (classic (m = 0)) as [|Hm0]. {
      rewrite H0 in H1. exfalso. apply (nat_irrefl 1)...
    }
    destruct (classic (m = 1)) as [|Hm1]. {
      rewrite H0. rewrite <- ordExp_2_ω in H...
    }
    rewrite <- IH, ordExp_limit in H... rewrite ordExp_limit...
    apply FUnionE in H as [k [Hk Hx]].
    eapply FUnionI... eapply ord_trans...
    rewrite fin_ordExp_eq_exp, fin_ordExp_eq_exp...
    apply exp_preserve_base_lt... intros H. subst.
    rewrite ordExp_0_r in Hx...
    rewrite one in Hx. apply SingE in Hx...
Qed.

Theorem ordTetL_n_ω : ∀n ∈ ω, 1 ∈ n → n ^^ᴸ ω = ω.
Proof with neauto.
  intros n Hn. ω_induction n; intros H1. exfalso0.
  assert (Hmp: m⁺ ∈ ω). apply ω_inductive...
  ext.
  - rewrite ordTetL_limit in H...
    apply FUnionE in H as [k [Hk Hx]]. eapply ω_trans...
  - apply le_iff_lt_suc in H1 as []...
    + rewrite <- IH, ordTetL_limit in H...
      rewrite ordTetL_limit...
      apply FUnionE in H as [k [Hk Hx]].
      eapply FUnionI... eapply ord_trans...
      apply tetL_preserve_base_lt... apply ord_gt_1_neq_0_1...
    + subst. rewrite <- ordTetL_2_ω in H...
Qed.
